services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 80
    networks:
      - pangolin
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  pangolin:
    external: true