services:
  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 3000
    networks:
      - pangolin
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M

networks:
  pangolin:
    external: true