services:
  mazanoke:
    image: ghcr.io/civilblur/mazanoke:latest
    container_name: mazanoke
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 80
    networks:
      - pangolin
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.10'
          memory: 128M

networks:
  pangolin:
    external: true